// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPagesMovie.Infrastructure.Data.DbContexts;

#nullable disable

namespace RazorPageMovie.Infrastructure.Data.Migrations;

[DbContext(typeof(RazorPagesMovieContext))]
partial class RazorPagesMovieContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("RazorPagesMovie.Models.Movie", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Genre")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<DateTime>("ReleaseDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Title")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Movie");
            });
#pragma warning restore 612, 618
    }
}


/*✅ S — Single Responsibility Principle (SRP)
Tem uma única responsabilidade: representar o modelo do banco de dados para migrações do EF Core.
Nenhuma lógica adicional. Atende SRP.

✅ O — Open/Closed Principle (OCP)
Classe gerada, não deve ser alterada manualmente, mas o EF Core a usa internamente para gerar migrações.
Está "fechada para modificações" do dev e "aberta" para o EF trabalhar.

✅ L — Liskov Substitution Principle (LSP)
Não aplicável diretamente, pois não é usada via polimorfismo, mas estende ModelSnapshot conforme esperado. Neutro.

✅ I — Interface Segregation Principle (ISP)
Não expõe interfaces, classe interna ao EF Core. Neutro.

✅ D — Dependency Inversion Principle (DIP)
Não depende diretamente de abstrações, é gerada e usada pelo framework EF Core internamente. Neutro. 
*/